/** Contrato das rotas da Fase 3. A especificação completa cresce nas fases seguintes. */
export const openApiFase3 = {
  openapi: '3.0.3',
  info: {
    title: 'Sistema de Candidatura a Vagas',
    version: '0.3.0',
  },
  paths: {
    '/auth/cadastro': { post: { operationId: 'cadastrar' } },
    '/auth/login': { post: { operationId: 'login' } },
    '/auth/refresh': { post: { operationId: 'refresh' } },
    '/auth/logout': { post: { operationId: 'logout' } },
    '/auth/recuperar': { post: { operationId: 'recuperarSenha' } },
    '/auth/redefinir': { post: { operationId: 'redefinirSenha' } },
    '/auth/confirmar-email': { post: { operationId: 'confirmarEmail' } },
    '/auth/mfa/iniciar': { post: { operationId: 'iniciarMfa' } },
    '/auth/mfa/confirmar': { post: { operationId: 'confirmarMfa' } },
    '/auth/mfa/verificar': { post: { operationId: 'verificarMfa' } },
    '/auth/reautenticar': { post: { operationId: 'reautenticar' } },
    '/me': { get: { operationId: 'me' } },
    '/me/visao': { patch: { operationId: 'alterarVisao' } },
    '/onboarding/candidato': { post: { operationId: 'onboardingCandidato' } },
    '/empresas/cadastro': { post: { operationId: 'cadastrarEmpresa' } },
    '/empresas/{empresaId}/verificacao/email': { post: { operationId: 'verificarEmailEmpresa' } },
    '/empresas/{empresaId}/verificacao/dominio': { post: { operationId: 'verificarDominio' } },
    '/empresas/{empresaId}/reenviar': { post: { operationId: 'reenviarVerificacao' } },
    '/empresas/{empresaId}/vagas/publicar': { post: { operationId: 'publicarVaga' } },
    '/empresas/{empresaId}/membros/convites': { post: { operationId: 'convidarMembro' } },
    '/empresas/{empresaId}/membros': { get: { operationId: 'listarMembros' } },
    '/convites/aceitar': { post: { operationId: 'aceitarConvite' } },
    '/empresas/{empresaId}/whatsapp/instancia': { post: { operationId: 'criarInstanciaWhatsapp' } },
    '/empresas/{empresaId}/whatsapp/conectar': { post: { operationId: 'conectarWhatsapp' } },
    '/empresas/{empresaId}/whatsapp/status': { get: { operationId: 'statusWhatsapp' } },
    '/empresas/{empresaId}/whatsapp/desconectar': { post: { operationId: 'desconectarWhatsapp' } },
    '/empresas/{empresaId}/auditoria': { get: { operationId: 'auditoriaEmpresa' } },
    '/admin/empresas': { get: { operationId: 'listarEmpresasAdmin' } },
    '/admin/empresas/fila': { get: { operationId: 'filaVerificacao' } },
    '/admin/empresas/{empresaId}/aprovar': { post: { operationId: 'aprovarEmpresa' } },
    '/admin/empresas/{empresaId}/rejeitar': { post: { operationId: 'rejeitarEmpresa' } },
    '/admin/empresas/{empresaId}/suspender': { post: { operationId: 'suspenderEmpresa' } },
    '/admin/empresas/{empresaId}/reativar': { post: { operationId: 'reativarEmpresa' } },
    '/admin/auditoria': { get: { operationId: 'auditoriaAdmin' } },
    '/admin/audios/{id}': { get: { operationId: 'lerAudioAdmin' } },
    '/admin/transcricoes/{id}': { get: { operationId: 'lerTranscricaoAdmin' } },
    '/admin/whatsapp/instancias': { get: { operationId: 'listarInstanciasAdmin' } },
    '/interno/empresas/{empresaId}/verificar-cnpj': { post: { operationId: 'jobVerificarCnpj' } },
    '/webhooks/whatsapp/uazapi/{instanciaId}': { post: { operationId: 'webhookWhatsapp' } },
  },
} as const;

export type CaminhoApi = keyof typeof openApiFase3.paths;
